id: P2E96B99A
initial_creation_type: input
source_metadata:
  title: Vajracchedikā Prajñāpāramitā
  language: zh
  volumes:
    a345a7d486e04f7794e57c1963c8ccaa:
      title: CIII_a
      base_file: CIII_a.txt
      work_id: WBE3F8BE8
    d6343e09c5e44bc39bc6cd7099af640b:
      title: CIII_b
      base_file: CIII_b.txt
      work_id: W32A5F254
    f91d556b6818454bbf97e5f3e41e5d3f:
      title: CIII_c
      base_file: CIII_c.txt
      work_id: W0DD841B4
    350849bdb58d4096ba88763756a8e976:
      title: CIII_d
      base_file: CIII_d.txt
      work_id: W81528D36
    2468fa6ec5ab494283c22389e6335307:
      title: CIII_e
      base_file: CIII_e.txt
      work_id: W8F4493C7
    b4702bef59834b688cd6daa3f5420193:
      title: CII_a
      base_file: CII_a.txt
      work_id: W3A199DAE
    325376fef3b6428bb6eeaa4a2b00a1c6:
      title: CII_b
      base_file: CII_b.txt
      work_id: W65222B56
    2e7ed8825b6b45b6a8869ea0e97cd00d:
      title: CII_c
      base_file: CII_c.txt
      work_id: W1D1DDA03
    74e92db1e77f4bdb870f575b8c395931:
      title: CIV_a
      base_file: CIV_a.txt
      work_id: W0733EFB3
    8d1d123d681a45f1b7f6bbd31a933858:
      title: CIV_b
      base_file: CIV_b.txt
      work_id: WB4A6F53C
    61f881892ae74b149d5114ea9a6ff215:
      title: CIV_c
      base_file: CIV_c.txt
      work_id: W4865A221
    b2e2d67fcc6f458685a31983836e4a5a:
      title: CIV_d
      base_file: CIV_d.txt
      work_id: WA491A773
    197e1ffb360a477391b19d98af0fd059:
      title: CIV_e
      base_file: CIV_e.txt
      work_id: W0638D69A
    74cf3382834e4317b0cec09b743338a2:
      title: CIV_f
      base_file: CIV_f.txt
      work_id: W5C7FB1A9
    292fb8b1349f425db332319aa82c3a10:
      title: CIV_g
      base_file: CIV_g.txt
      work_id: W430DC0D0
    768307703cb54286b2a5703b86415e61:
      title: CIV_h
      base_file: CIV_h.txt
      work_id: W4E40E77C
    3f4cc3089a8d4afbb9be2ebd0a25910a:
      title: CIX_a
      base_file: CIX_a.txt
      work_id: W1AE2BF61
    723ce968334f49db96517c1f854e23e8:
      title: CIX_b
      base_file: CIX_b.txt
      work_id: WD31814CF
    497a4a6576554e8a9a9125ddb841f5c4:
      title: CI_a
      base_file: CI_a.txt
      work_id: WAB881BD5
    523be8613a444138b9fbbb8692291dd7:
      title: CI_b
      base_file: CI_b.txt
      work_id: W266CC0CA
    72abb18d05fd4e9286cd3d392a66f08f:
      title: CI_c
      base_file: CI_c.txt
      work_id: W3C49C339
    bdcf3047b9e54412a2e9514d699562dc:
      title: CI_d
      base_file: CI_d.txt
      work_id: W9F64E038
    0b083ea4c8104aabbc539a8dc459a2e8:
      title: CI_e
      base_file: CI_e.txt
      work_id: WA50A0A62
    e926cea47bc44b61924af4bc355ddf6e:
      title: CVIII_a
      base_file: CVIII_a.txt
      work_id: WE7C5F2BD
    3cfceea9a9b54417801a4ee18c9f4cf1:
      title: CVIII_b
      base_file: CVIII_b.txt
      work_id: WCFECEEEE
    abd69adab36c455fbed2735ec57fba2f:
      title: CVII_a
      base_file: CVII_a.txt
      work_id: W67A98290
    ee84e29ca0284e7bbccaceae3381ecf0:
      title: CVII_b
      base_file: CVII_b.txt
      work_id: W2FB32192
    94e570cfbf054bacae57330adfa33e7b:
      title: CVII_c
      base_file: CVII_c.txt
      work_id: W1DD5AA93
    85dd2f2f4e664f35a8073c957d59427a:
      title: CVII_d
      base_file: CVII_d.txt
      work_id: W6DAFCA2C
    4072200a1c2443bab4d55451c2a0c1b8:
      title: CVII_e
      base_file: CVII_e.txt
      work_id: W76BCFDBA
    5685a0d9a47444eaa710dacae4e27282:
      title: CVII_f
      base_file: CVII_f.txt
      work_id: W04B5766C
    0e6f6781b7a94957a1b4de2c592ce203:
      title: CVII_g
      base_file: CVII_g.txt
      work_id: WD4393AD9
    b85e901884f44f6183182b38efd34272:
      title: CVII_h
      base_file: CVII_h.txt
      work_id: W9B666556
    f35d5682e3a44f038d35c395f5680efd:
      title: CVI_a
      base_file: CVI_a.txt
      work_id: WD6D03EF0
    62b4f66b94cc444eab4a376f3972b1e1:
      title: CVI_b
      base_file: CVI_b.txt
      work_id: W7BB97E1D
    e282b91071d34078adbe532fa2ac52a0:
      title: CVI_c
      base_file: CVI_c.txt
      work_id: W0308444E
    08fd658f73cf4ceabe143477ddb8259c:
      title: CV_a
      base_file: CV_a.txt
      work_id: W4155794A
    3c8e944bf673461d9c600d610b5d8e33:
      title: CV_b
      base_file: CV_b.txt
      work_id: WE08D0E44
    b65d7f71476e4d33a60a78d4b3e294f1:
      title: CV_c
      base_file: CV_c.txt
      work_id: WA13A110E
    186451ef8cc54360a80db4c12c68f044:
      title: CXIII_a
      base_file: CXIII_a.txt
      work_id: W05B5A5B9
    ad7fc8846ef04439887029264d08c7af:
      title: CXIII_b
      base_file: CXIII_b.txt
      work_id: W41B44975
    c92e9df7c70c4523bfd70ffc90827a8d:
      title: CXII_a
      base_file: CXII_a.txt
      work_id: WDE891E7C
    ec3f2c2db7b7479b95ec4b5abc357a9d:
      title: CXII_b
      base_file: CXII_b.txt
      work_id: WE66ABA8C
    0391d32911ea4f3f821a5e40e5fe8640:
      title: CXIV_a
      base_file: CXIV_a.txt
      work_id: WFF24A5EE
    bb6ff1d9162c427cab33be883b600510:
      title: CXIV_b
      base_file: CXIV_b.txt
      work_id: WC2A68FB6
    d0f2b7d2309046eea93fa399273d8dcb:
      title: CXI_a
      base_file: CXI_a.txt
      work_id: W993AA69A
    b5400e5b5a7149dc8fdf6410d1473108:
      title: CXV_a
      base_file: CXV_a.txt
      work_id: W349177D7
    0cca7b102d3949c190e46be85599db6b:
      title: CXV_b
      base_file: CXV_b.txt
      work_id: W6260B6AB
    f488f4febfa1433e950557dbf660c435:
      title: CX_a
      base_file: CX_a.txt
      work_id: W42CB2E90
    337addf5dc0140c18daa157eb0559523:
      title: CX_b
      base_file: CX_b.txt
      work_id: W4C5CD01C
    60a3123e1de54c97b0b40089d9a62a5d:
      title: Colophon
      base_file: Colophon.txt
      work_id: WB113FCF1
    f861c197e75d494a82325e7b77c78793:
      title: Preface
      base_file: Preface.txt
      work_id: WEB5A2A90
    381cbfb5c79e4a5781e69662dd86241c:
      title: Title
      base_file: Title.txt
      work_id: W44EE3370
    27b252b734bc435b99db669023be5fd8:
      title: §1
      base_file: §1.txt
      work_id: W75896625
    32f5bd6a06844d8c8a5d32e91a675931:
      title: §11
      base_file: §11.txt
      work_id: W75DAF816
    750bafbfddd24945aa33d38b44112df8:
      title: §12
      base_file: §12.txt
      work_id: W7084FBFE
    366f3912157b4fe3a06d73b5b9d50b14:
      title: §2
      base_file: §2.txt
      work_id: WB945F4E9
    f921eb41dc9d4defaa0fa31359a48fbf:
      title: §23
      base_file: §23.txt
      work_id: W6AE15922
    a5c90d9c13bc499da4173f809b5695a8:
      title: §24
      base_file: §24.txt
      work_id: W7309F85E
    173d2c9b13fe42419bf2fb8000de7b00:
      title: §25
      base_file: §25.txt
      work_id: WE4410074
    b0d55a368a114587b1ec1f9a92e15a61:
      title: §27
      base_file: §27.txt
      work_id: W7D86B4AB
    c20225325b2644a6bac48840b63f6d45:
      title: §28
      base_file: §28.txt
      work_id: W03552C6B
    76b7d716391b46b4a3d344aa108c5a39:
      title: §29
      base_file: §29.txt
      work_id: WAA6B6043
    d11408e547ee4aca8a85322d429c0262:
      title: §3
      base_file: §3.txt
      work_id: W1D0C4CA8
    bf62e99a8dc24e05898a4ab72208fc0e:
      title: §4
      base_file: §4.txt
      work_id: WCFFE4FE6
    65fb5cf4478e439ca7fe332fc3326376:
      title: §5
      base_file: §5.txt
      work_id: W24F8098D
    37a346cf7ffc4ca88dff484d9273672e:
      title: §6
      base_file: §6.txt
      work_id: W66B486B0
    956485ecfd2b49eb91df1b1fad7de16a:
      title: §7
      base_file: §7.txt
      work_id: WD70C9024
    cb1fa47fdcfd4e14921684a58d3986c9:
      title: §8
      base_file: §8.txt
      work_id: WA2A0CF0F
  chapter_to_tile:
    CI: §9
    CII: §10
    CIII: §13
    CIV: §14
    CV: §15
    CVI: §16
    CVII: §17
    CVIII: §18
    CIX: §19
    CX: §21
    CXI: §22
    CXII: §26
    CXIII: §30
    CXIV: §31
    CXV: §32
created_at: '2022-03-01T21:55:01.801229'
last_modified_at: '2022-03-01T21:55:01.801237'
